# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ZWLiving' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.8.2'
  pod 'Masonry', '~> 1.0.2'
  pod 'YYKit', '~> 1.0.9'
  pod 'MJExtension'
  pod 'LFLiveKit'
end
